colcon/colcon.readthedocs.org

developer/bootstrap.rst
i think the `--base-paths` argument got renamed
=> base-paths --> --paths

developer/bootstrap.rst
=> add missing cd to source instructions

migration/ament_tools.rst, migration/catkin_make_isolated.rst, migration/catkin_tools.rst, user/quick-start.rst
CLI changes from colcon/colcon-package-selection#2 and colcon/colcon-package-selection#4. Waiting for the changes to be released before merging.
=> update naming of --package* arguments

migration/ament_tools.rst, migration/catkin_make_isolated.rst, migration/catkin_tools.rst
Connect to colcon/colcon-cmake#6.
=> remove escaped leading space example since it doesn't work on Windows

developer/bootstrap.rst, user/quick-start.rst
Connect to colcon/colcon-core#38.
=> rename prefix script into local_setup

user/quick-start.rst
Related to colcon/colcon-ros#11.
=> add note about catkin version

user/installation.rst
Related to colcon/colcon-argcomplete#8.
=> add note for argcomplete suffix

.travis.yml
https://pypi.org/project/doc8/
=> add doc8 check to Travis

spelling_wordlist.txt, user/installation.rst
Add instructions to install `colcon` using Debian packages.
=> add Debian package instructions

requirements.txt
=> add pytest-runner to requirements.txt

user/how-to.rst
Documenting missing part of this question: colcon/colcon-core#102
=> add how-to for console cohesion

requirements.txt
=> add distlib to requirements.txt

migration/catkin_tools.rst, user/quick-start.rst
=> fixed typo

user/quick-start.rst
Follow up of colcon/colcon-ros#48.
=> update instructions for ROS 1 test targets

developer/contribution.rst
Fix invalid markup being rendered as plain text.
=> fix markdown links to use rst markup

developer/changelog.rst, index.rst, spelling_wordlist.txt
Document how changelogs are being managed for most colcon packages.
=> add information about changelogs

migration/ament_tools.rst
Closes colcon/colcon-core#164.
=> mention migration for --make-flags from ament_tools

user/quick-start.rst
Especially for new users, it is nice if all commands are given.
=> Give all commands

colcon.repos, user/installation.rst
https://github.com/colcon/colcon-cd
=> add colcon-cd repo as well as instructions how to use it

developer/extension-point.rst, index.rst, spelling_wordlist.txt
Based on questions in colcon/colcon-core#262.
=> add brief description of common extension points

index.rst
=> fix link to latest state of the docs

user/quick-start.rst
Signed-off-by: maryaB-osr <marya@openrobotics.org>
=> Change list -g to graph in quick start

reference/verb/test.rst
Added in colcon/colcon-core#292.
=> add --pytest-with-coverage option to reference

spelling_wordlist.txt
Follow up of #63 which didn't run CI.
=> add new word to wordlist

spelling_wordlist.txt, user/how-to.rst
Document the feature from colcon/colcon-cmake#69.
=> howto compile_commands.json

reference/package-selection-arguments.rst
Follow-up to https://github.com/colcon/colcon-package-selection/pull/36
=> Document --packages-up-to-regex

developer/contribution.rst, spelling_wordlist.txt
To clarify expectations for documentation contributions.
=> mention one-sentence-per-line style for docs

index.rst
Revert unintentional / unrelated changes from #67.
=> remove unintentional / unrelated changes from #67

reference/global-arguments.rst
Documenting the change from colcon/colcon-core#363.
=> update the environment variable name to block certain extensions

.github/workflows/ci.yml, Makefile
To prevent warnings going unnoticed.
=> fail CI in case sphinx has warnings

index.rst, user/how-to.rst, user/isolated-vs-merged-workspaces.rst, user/log-files.rst, user/overriding-packages.rst, user/using-multiple-workspaces.rst, user/what-is-a-workspace.rst
This adds documentation about known issues with overriding packages. I'm opening a PR for feedback.
Part of ros2/ros2#1150
=> Add documentation about workspaces, including overriding packages

.readthedocs.yaml, conf.py, dependencies.txt, reference/discovery-arguments.rst, reference/event-handler-arguments.rst, reference/executor-arguments.rst, reference/global-arguments.rst, reference/mixin-arguments.rst, reference/package-selection-arguments.rst, reference/verb/build.rst, reference/verb/graph.rst, reference/verb/list.rst, reference/verb/test-result.rst, reference/verb/test.rst
.readthedocs.yaml file is now required by readthedocs
Also needed to add some missing dependencies/tools, and fix some formatting.
=> Restore ability to build properly
