index.rst
spelling_wordlist.txt
user/configuration.rst

In the current implementation you need to use underscores for the configuration options (instead of the dashes on the command line). Behind the scene it uses the `dest` of each argument.
I wanted to open this for visibility anyway since it already provides helpful information. I will create PRs to modify the behavior to match the documentation before this is being merged.

add documentation for configuration files

---

developer/bootstrap.rst

Addresses the problem described in colcon/colcon-notification#4.

add notes for Windows

---

index.rst

I am not aware of a way to highlight the version the user is currently seeing. If anybody has a suggestion how to achieve that I would be more than happy to integrate that feature.

add note about released and latest docs

---

developer/bootstrap.rst
requirements.txt

Reverts colcon/colcon.readthedocs.org#11
This instructions is not necessary since all `colcon` package which need `EmPy` declare it as an `install_requires`, e.g. https://github.com/colcon/colcon-core/blob/89edc0fb605edd8980fd1d4c25c6fd5095cc6ab4/setup.cfg#L28.

add requirements.txt file

---

requirements.txt

Fixes colcon/colcon-core#20.
Collected from the `install_requires` of all common extensions.

list optional dependencies in requirements.txt

---

migration/ament_tools.rst

attempt to clarify the behavior of --repeat-until-fail depending on the type of tests.
Also fixed the original description that suggested the tests are ran N times and repeated N times
related to https://github.com/ros2/build_cop/issues/121

clarify current behavior of repeat-until-fail for pytest tests

---

index.rst
spelling_wordlist.txt
user/how-to.rst

The page added in this patch describes common tasks:
* Show all output immediately on the console
* Build only a single package (or selected packages)
* Build selected packages including their dependencies
* Run specific tests
* Enable additional output for debugging
* Log files of past invocations

add how-to page with common use cases / questions

---

colcon.repos

`colcon-ros` requires `colcon-pkg-config`. If it is missing then a traceback is printed for every package when bootstrapping colcon using these instructions https://colcon.readthedocs.io/en/released/developer/bootstrap.html
```
[1.783s] ERROR:colcon.colcon_core.entry_point:Exception loading extension 'colcon_core.task.build.ros': The 'colcon-pkg-con
fig' distribution was not found and is required by the application
Traceback (most recent call last):
File "/home/developer/cc_ws/install/colcon-core/lib/python3.6/site-packages/colcon_core/entry_point.py", line 98, in load
_entry_points
extension_type = load_entry_point(entry_point)
File "/home/developer/cc_ws/install/colcon-core/lib/python3.6/site-packages/colcon_core/entry_point.py", line 140, in loa
d_entry_point
return entry_point.load() …
```

Add colcon-pkg-config

---

migration/ament_tools.rst
migration/catkin_make_isolated.rst
migration/catkin_tools.rst

Remove space prefix from common arguments (except if they collide with colcon arguments).
This is not needed anymore since colcon/colcon-core#63 was implemented.

remove obsolete space prefix

---

user/quick-start.rst

See https://github.com/colcon/colcon-core/issues/103

Replace `catkin` mis-reference with `colcon`

---

requirements.txt
user/installation.rst

Update docs about the location of the `colcon-argcomplete` hooks which are changing as of colcon/colcon-argcomplete#21.

update argcomplete hook location

---

colcon.repos

I went through the build from source instructions trying to setup the `mixin` verb, but that repo was missing from the given list.

Added colcon-mixin to the source colcon repos

---

conf.py
developer/program-flow.rst
index.rst

Based on questions in colcon/colcon-core#262.
The `list` verb diagram: 
The `build` verb diagram:

add high level program flow for list and build verbs

---

user/configuration.rst

As implemented in colcon/colcon-defaults#22.

document default values for root parser arguments

---

index.rst
reference/package-selection-arguments.rst
user/how-to.rst

Document easier usage using the new option added in colcon/colcon-package-selection#35,

document --packages-above-and-dependencies instead of nested invocation of build and list

---

index.rst
reference/verb/edit.rst

Addresses https://github.com/colcon/colcon-ed/issues/12
This PR adds the documentation for [**colcon-ed**](https://github.com/colcon/colcon-ed) .
I added in another verb inside the reference folder.
I also find that in PR #68 and my own CI [log](https://travis-ci.org/github/Briancbn/colcon.readthedocs.org/builds/687946664) there is an error during `sudo apt-get update` 
It is mainly due to some google-chrome keys couldn't be verified. I added in a simple fix that will add the updated keys for google. I am not sure it is the best solution, but it does the job for now.
https://github.com/colcon/colcon.readthedocs.org/blob/c3e89cd231301b12b1da91a4769928a22db47e9e/.travis.yml#L6

Add in documentation for colcon-ed

---

reference/global-arguments.rst

Related to colcon/colcon-output#33.

mention elapsed time prefix in streams.log

---

developer/release.rst
index.rst
spelling_wordlist.txt

Instructions how to use https://github.com/dirk-thomas/publish-python and upload Debian artifacts to `packagecloud.io`

add documentation how to release Python packages with colcon extensions

---

user/how-to.rst

Current PR fixes an undefined label reported when running `make html` manually.
```
writing output... [100%] user/quick-start
/home/berger/src/colcon/colcon.readthedocs.org/user/how-to.rst:81: WARNING: undefined label: rebuild_packages_ (if the link has no caption the label must precede a section header)
generating indices...  genindexdone
```
Here's how the section at hand looks before and after the fix:
Before:
After:
Would it  be worth checking for broken links as part of the CI?
There's the sphinx `linkcheck` script which can be used for such purpose: `sphinx-server sphinx-build -b linkcheck`
https://www.sphinx-doc.org/en/master/_modules/sphinx/builders/linkcheck.html

Fix undefined label

---

developer/bootstrap.rst
developer/environment.rst
user/quick-start.rst

- Typo: s/us/use
- Package shell script is stored under `<package_name>/share/<package_name>/... .<ext>` with regards to install directory
- Amend Gazebo-colcon description

Do minor documentation changes

---

reference/mixin-arguments.rst

add warning about lack of semantic when merging mixin list values

---

reference/executor-arguments.rst

reference os.cpu_count() for --parallel-workers

---

user/isolated-vs-merged-workspaces.rst
user/using-multiple-workspaces.rst
user/what-is-a-workspace.rst

Follow up from #88, this converts tabs to 4 spaces to make a job that runs against the `main` branch happy: https://github.com/colcon/colcon.readthedocs.org/pull/88#issuecomment-1142892966
```
sed  -i "s/\t/    /g" what-is-a-workspace.rst isolated-vs-merged-workspaces.rst overriding-packages.rst log-files.rst using-multiple-workspaces.rst
```

4 spaces instead of tabs

---

requirements.txt

Pins `EmPy<4` to fix the error:
ImportError: cannot import name 'OVERRIDE_OPT' from 'em'
This fixes the "Bootstrap from source" instructions, which is using this file to install requirements.

Fix bootstrap from source instructions

---

developer/release.rst

Upstream appears to be abandoned.

Use colcon fork of publish-python
